version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@pulumi/aws"
    versions:
    - 3.25.1
    - 3.26.1
    - 3.27.0
    - 3.28.0
    - 3.28.1
    - 3.29.0
    - 3.29.1
    - 3.30.0
    - 3.30.1
    - 3.31.0
    - 3.32.0
    - 3.32.1
    - 3.32.2
  - dependency-name: lighthouse
    versions:
    - 7.0.1
    - 7.1.0
    - 7.2.0
  - dependency-name: "@pulumi/pulumi"
    versions:
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
  - dependency-name: "@pulumi/cloudflare"
    versions:
    - 2.12.0
    - 2.13.0
    - 2.13.1
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
