version: 2.1
orbs:
  codecov: codecov/codecov@1.0.1
  docker-publish: circleci/docker-publish@0.1.0
jobs:
  test:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run:
          name: Test with coverage
          command: lein cloverage --codecov --junit
      - save_cache:
          name: Store lein cache
          key: v1-dependencies-{{ checksum "project.clj" }}
          paths:
            - ~/.m2
      - codecov/upload:
          file: target/coverage/codecov.json
          flags: unittests
      - store_artifacts:
          path: target/coverage/
          destination: test-results
      - store_test_results:
          path: target/coverage/
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
      - run:
          name: Build uberjar
          command: lein uberjar
      - persist_to_workspace:
          root: .
          paths: target/app-standalone.jar

workflows:
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - docker-publish/publish:
          after_checkout:
            - attach_workspace:
                at: .
          requires:
            - build
          filters:
            branches:
              only: master
