# yaml-language-server: $schema=https://json.schemastore.org/circleciconfig.json
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8
  node: circleci/node@5.2.0
  php: circleci/php@1.1.0
  pulumi: pulumi/pulumi@2.1.0

executors:
  pw-focal-development:
    docker:
      - image: mcr.microsoft.com/playwright:v1.43.1-focal

commands:
  install_browsers:
    steps:
      - restore_cache:
          name: Restore Playwright browsers
          keys:
            - v2-browsers-{{ checksum "cards/package.json" }}
      - run:
          name: Install Playwright browsers
          command: yarn playwright install --with-deps chromium
          working_directory: cards
      - save_cache:
          name: Cache Playwright browsers
          key: v2-browsers-{{ checksum "cards/package.json" }}
          paths:
            - ~/.cache/ms-playwright

jobs:
  provision:
    docker:
      - image: cimg/node:current
    resource_class: arm.large
    steps:
      - checkout
      - pulumi/login
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v1-provision
          override-ci-command: yarn workspaces focus @rarousnet/infrastructure
      - pulumi/update:
          working_directory: infrastructure
          stack: prod
          skip-preview: true
  generate:
    resource_class: large
    docker:
      - image: cimg/clojure:1.11-node
        environment:
          LEIN_JVM_OPTS: "-Xmx400m"
          JVM_OPTS: "-Xmx3200m"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install
      - node/install-yarn
      - php/install-php:
          version: "$(jq --raw-data '.platform.php' generator/composer.lock)"
      - php/install-composer
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v2-build
          override-ci-command: yarn workspaces focus @rarousnet/website
      - php/install-packages:
          app-dir: ~/project/generator
          install-flags: --ignore-platform-reqs --no-interaction --prefer-dist
      - restore_cache:
          name: Restore deps cache
          keys:
            - v4-dependencies-{{ checksum "generator/deps.edn" }}
      - run:
          name: Build website
          command: yarn build:website
      - save_cache:
          name: Store deps cache
          key: v4-dependencies-{{ checksum "generator/deps.edn" }}
          paths:
            - ~/.m2
            - generator/.cpcache
      - persist_to_workspace:
          root: .
          paths: .gryphoon
  postprocess:
    resource_class: large
    executor: pw-focal-development
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v3-pw
          override-ci-command: yarn workspaces focus rarousnet @rarousnet/cards
      - install_browsers
      - run:
          name: Generate Twitter Card images
          command: node ./cards/generator.js "file://`pwd -P`/cards/card.html"
      - run:
          name: Generate search index
          command: yarn build:index
      - persist_to_workspace:
          root: .
          paths: .gryphoon
  test:
    docker:
      - image: cimg/node:20.12-browsers
    resource_class: large
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          sudo apt-get update
          sudo apt-get install libnss3-tools
      - browser-tools/install-chrome
      - node/install
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v2-test
          override-ci-command: yarn workspaces focus rarousnet
      - run:
          name: Install self-signed cert for localhost
          command: |
            mkdir -p $HOME/.pki/nssdb
            echo "Cert path: ./node_modules/lws/ssl/lws-cert.pem"
            certutil -N -d $HOME/.pki/nssdb --empty-password
            certutil -A -d sql:$HOME/.pki/nssdb -t TC -n lws-cert -i ./node_modules/lws/ssl/lws-cert.pem
            certutil -L -d sql:$HOME/.pki/nssdb
      - run:
          name: Serve site content
          command: yarn serve
          background: true
      - run:
          name: Test site with Lighthouse
          command: |
            yarn test:lighthouse
            yarn test:ava
      - store_artifacts:
          path: ./results
      - store_test_results:
          path: ./results
  pages_deploy:
    docker:
      - image: cimg/node:20.12
    resource_class: arm.large
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v4-publish
          override-ci-command: yarn workspaces focus rarousnet @rarousnet/functions
      - run:
          name: Publish to Cloudflare Pages
          command: npx wrangler pages deploy .gryphoon/dist --project-name=rarousnet
workflows:
  build_and_deploy:
    jobs:
      - generate
      - postprocess:
          requires:
            - generate
      - provision:
          context: aws
          filters:
            branches:
              only: trunk
      - test:
          requires:
            - postprocess
      - pages_deploy:
          context: cloudflare
          requires:
            - provision
            - test
          filters:
            branches:
              only: trunk
