version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1
  aws-s3: circleci/aws-s3@3.0.0
  cloudflare: katana/cloudflare@1.0.0
  github: topmonks/github@1.2.0
  node: circleci/node@5.0.3
  php: circleci/php@1.1.0
  pulumi: pulumi/pulumi@2.1.0

commands:
  install_browsers:
    steps:
      - run:
          command: |
            sudo apt-get update
            sudo apt-get upgrade
      - restore_cache:
          name: Restore Playwright browsers
          keys:
            - v2-browsers-{{ checksum "package.json" }}
      - run:
          name: Install Playwright browsers
          command: yarn playwright install --with-deps chromium
      - save_cache:
          name: Cache Playwright browsers
          key: v2-browsers-{{ checksum "package.json" }}
          paths:
            - ~/.cache/ms-playwright

jobs:
  provision:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - pulumi/login
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1-prod
      - pulumi/update:
          stack: prod
          skip-preview: true
  generate:
    docker:
      - image: circleci/clojure:openjdk-16-tools-deps-buster
        environment:
          LEIN_JVM_OPTS: "-Xmx400m"
          JVM_OPTS: "-Xmx3200m"
    steps:
      - checkout
      - php/install-php
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore deps cache
          keys:
            - v3-dependencies-{{ checksum "generator/deps.edn" }}
      - run:
          name: Generate static web site content
          working_directory: generator
          command: clojure -m rarousnet.generator ../
      - save_cache:
          name: Store deps cache
          key: v3-dependencies-{{ checksum "generator/deps.edn" }}
          paths:
            - ~/.m2
            - generator/.cpcache
      - persist_to_workspace:
          root: .
          paths: dist
  postprocess:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v2
      - install_browsers
      - run:
          name: Generate Twitter Card images
          command: |
            mv ./dist/weblog/data.json ./cards
            node ./cards/generator "file://`pwd -P`/cards/card.html"
      - run:
          name: Postprocess resources
          command: yarn build:assets
      - persist_to_workspace:
          root: .
          paths: dist
  test:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install
      - node/install-yarn
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v2
      - run:
          name: Install Ubuntu packages
          command: sudo apt install chromium-browser libnss3-tools
      - run:
          name: Install self-signed cert for localhost
          command: |
            mkdir -p $HOME/.pki/nssdb
            echo "Cert path: ./node_modules/lws/ssl/lws-cert.pem"
            certutil -N -d $HOME/.pki/nssdb --empty-password
            certutil -A -d sql:$HOME/.pki/nssdb -t TC -n lws-cert -i ./node_modules/lws/ssl/lws-cert.pem
            certutil -L -d sql:$HOME/.pki/nssdb
      - run:
          name: Serve site content
          command: yarn serve
          background: true
      - run:
          name: Test site with Lighthouse
          command: |
            mkdir results
            yarn test:lighthouse
            yarn test:ava
      - store_artifacts:
          path: ./results
      - store_test_results:
          path: ./results
  s3_deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-s3/sync:
          arguments: |
            --size-only \
            --quiet
          from: dist/
          to: s3://www.rarous.net/
      - aws-s3/copy:
          arguments: |
            --exclude "*" \
            --include "*.rss" \
            --content-type="application/rss+xml; charset=utf-8" \
            --metadata-directive="REPLACE" \
            --recursive
          from: s3://www.rarous.net/
          to: s3://www.rarous.net/
      - cloudflare/purge-cache
  merge_pr:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - github/install
      - github/merge_pr:
          rebase: true
workflows:
  build_and_deploy:
    jobs:
      - generate
      - postprocess:
          requires:
            - generate
      - provision:
          context: aws
          filters:
            branches:
              only: master
      - test:
          requires:
            - postprocess
      - merge_pr:
         context: github-cli
         requires:
           - test
         filters:
           branches:
             only: /revovate\/.*/
      - s3_deploy:
          context:
            - aws
            - cloudflare-invalidation
          requires:
            - provision
            - test
          filters:
            branches:
              only: master
