environment:
  - rarous-cloudflare
  - rarous-discogs
  - rarous-spotify
config:
  rarousnet:domain: www.rarous.net
  rarousnet:google-auth-clientId: 218256334208-115s3k0ciq53s7fj5u7k8hg70oqfu9j5.apps.googleusercontent.com
  rarousnet:rollbar-token: 16eb2b188b784fada411b451d37848ee
  rarousnet:webhook-secret:
    secure: AAABAMDlnk5eyssfU+XvFCw8R3vZApfj1ZWdi/i8J7VlS9h0tF+tnLWhPBwcSSvvE/JYyX0FOtufVrx2jOOkiwEgY06mxmw86yTLLf43ZInf7Q==
  rarousnet:weblog-cards-secret:
    secure: AAABAPUMti3n0lkVWaFF6cgCIzbVA9P7369ij1K3o05TNPgPtZ76JtdYb07lmix4ufWaUf9YChnFOM22kCrRoPrD1eiSppo7D7KW/GQABACTVQ==
  rarousnet:screenshotter-secret:
    secure: AAABAI7bY3VE5h7lYuhqG/iTGlunLJjFyaz69IE7qKlxoL7/Kw41ZInblVeuryvjL5rEEvU0ztNmA/8hUaPrPAPu6yh2/tov5AEO+GOwEImpKA==
  rarousnet:semantic-extractor-secret:
    secure: AAABAJ0K+ceDmeXH6d1sgcxbScW3a/+J7iWmWX5BIKh9Ui9NnFVAuXTCbEw6zuBkiznqMu3DlzXy1v4exQVDhVe0BW1PN6j5aynAJjrecvwkLyGVw4vowXW0+01qSL3G
  rarousnet:private-key:
    secure: AAABAJR+7mKJfEMhRDhwQ/n4u/JQxNTKqRZQ4LpUvTF361fbkjyCpjqlleD3ugwyUapRhQU9YiDzNy7XFLq82SbLuxtA5DBts8rCyT21sb0L2Bux5tmq/qYNlieQ7vQ+
